"""add group_rotation and duty_assignment models

Revision ID: 04bafd4cbba5
Revises: b2c3d4e5f6a1
Create Date: 2026-03-18 19:03:07.564667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bafd4cbba5'
down_revision = 'b2c3d4e5f6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practical_day_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('duty_type', sa.Enum('Saaldienst', 'Entsorgungsdienst', name='duty_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['practical_day_id'], ['practical_day.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_rotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practical_day_id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.Enum('A', 'B', 'C', 'D', name='group_code_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['practical_day_id'], ['practical_day.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practical_day_id', 'group_code')
    )
    with op.batch_alter_table('method_reagent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_method_reagent_single_titrant'), sqlite_where=sa.text('is_titrant = 1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('method_reagent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_method_reagent_single_titrant'), ['method_id'], unique=1, sqlite_where=sa.text('is_titrant = 1'))

    op.drop_table('group_rotation')
    op.drop_table('duty_assignment')
    # ### end Alembic commands ###
