"""initial schema

Revision ID: 6ffd420381fb
Revises: 
Create Date: 2026-03-18 17:25:39.059665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffd420381fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Drop legacy partial index if it exists (may be absent on older installs)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'method_reagent' in inspector.get_table_names():
        existing = {idx['name'] for idx in inspector.get_indexes('method_reagent')}
        if 'uq_method_reagent_single_titrant' in existing:
            with op.batch_alter_table('method_reagent', schema=None) as batch_op:
                batch_op.drop_index(batch_op.f('uq_method_reagent_single_titrant'), sqlite_where=sa.text('is_titrant = 1'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('method_reagent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_method_reagent_single_titrant'), ['method_id'], unique=1, sqlite_where=sa.text('is_titrant = 1'))

    # ### end Alembic commands ###
