"""add protocol_check model

Revision ID: 75ce3436b714
Revises: 04bafd4cbba5
Create Date: 2026-03-18 19:29:46.501667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ce3436b714'
down_revision = '04bafd4cbba5'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'protocol_check' in inspector.get_table_names():
        return  # already present (fresh install via db.create_all in initial migration)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_assignment_id', sa.Integer(), nullable=False),
    sa.Column('checked_date', sa.String(length=20), nullable=False),
    sa.Column('checked_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['sample_assignment_id'], ['sample_assignment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_assignment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol_check')
    # ### end Alembic commands ###
