"""add group_code to student

Revision ID: a1b2c3d4e5f6
Revises: 6ffd420381fb
Create Date: 2026-03-18 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '6ffd420381fb'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_cols = {col['name'] for col in inspector.get_columns('student')}
    if 'group_code' in existing_cols:
        return  # already present (fresh install via db.create_all in initial migration)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_code', sa.Enum('A', 'B', 'C', 'D', name='group_code_enum', native_enum=False, create_constraint=True, validate_strings=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('group_code')

    # ### end Alembic commands ###
